const CONFIG_META = {
  "auth.captcha.enabled": {
    label: "登录验证码",
    group: "auth",
    groupLabel: "认证与安全",
    description: "开启后登录页显示验证码输入项。",
    impact: "登录页",
    riskLevel: "中",
    control: "boolean",
    defaultValue: "false",
  },
  "security.password.minLength": {
    label: "密码最小长度",
    group: "auth",
    groupLabel: "认证与安全",
    description: "新密码最少字符数。",
    impact: "用户改密、重置密码",
    riskLevel: "中",
    control: "number",
    min: 6,
    max: 64,
    defaultValue: "8",
  },
  "auth.session.idleTimeoutSeconds": {
    label: "会话空闲超时（秒）",
    group: "auth",
    groupLabel: "认证与安全",
    description: "超时后需要重新登录。",
    impact: "全站会话",
    riskLevel: "高",
    control: "number",
    min: 300,
    max: 604800,
    defaultValue: "1800",
  },
  "file.upload.maxSizeMB": {
    label: "上传大小上限（MB）",
    group: "file",
    groupLabel: "文件与上传",
    description: "单文件上传体积上限。",
    impact: "文件上传",
    riskLevel: "低",
    control: "number",
    min: 1,
    max: 2048,
    defaultValue: "20",
  },
  "file.upload.allowedTypes": {
    label: "允许上传类型",
    group: "file",
    groupLabel: "文件与上传",
    description: "逗号分隔扩展名。",
    impact: "文件上传",
    riskLevel: "低",
    control: "text",
    defaultValue: "jpg,png,pdf",
  },
  "notify.email.enabled": {
    label: "邮件通知开关",
    group: "notify",
    groupLabel: "通知与消息",
    description: "控制邮件通知是否发送。",
    impact: "消息通知",
    riskLevel: "低",
    control: "boolean",
    defaultValue: "false",
  },
  "notify.retry.maxAttempts": {
    label: "通知重试次数",
    group: "notify",
    groupLabel: "通知与消息",
    description: "发送失败重试次数。",
    impact: "消息通知",
    riskLevel: "低",
    control: "number",
    min: 0,
    max: 20,
    defaultValue: "3",
  },
  "ui.theme.default": {
    label: "默认主题",
    group: "ui",
    groupLabel: "界面与体验",
    description: "控制系统浅色/深色主题。",
    impact: "全站界面",
    riskLevel: "低",
    control: "select",
    options: [
      { value: "light", label: "浅色" },
      { value: "dark", label: "深色" },
    ],
    defaultValue: "light",
  },
  "ui.page.defaultSize": {
    label: "默认分页条数",
    group: "ui",
    groupLabel: "界面与体验",
    description: "列表默认每页展示条数。",
    impact: "列表页面",
    riskLevel: "低",
    control: "number",
    min: 10,
    max: 200,
    defaultValue: "20",
  },
};

export const GROUP_ORDER = ["auth", "file", "notify", "ui", "other"];

export default CONFIG_META;
