import { createElement } from "react";
import {
  AlertOutlined,
  ApartmentOutlined,
  ApiOutlined,
  AppstoreAddOutlined,
  AppstoreOutlined,
  AreaChartOutlined,
  AuditOutlined,
  BankOutlined,
  BarChartOutlined,
  BellOutlined,
  BlockOutlined,
  BookOutlined,
  BranchesOutlined,
  BugOutlined,
  BulbOutlined,
  CalendarOutlined,
  CameraOutlined,
  CarryOutOutlined,
  CheckOutlined,
  ClockCircleOutlined,
  CloseOutlined,
  CloudOutlined,
  CloudUploadOutlined,
  CodeOutlined,
  CommentOutlined,
  CompassOutlined,
  ContactsOutlined,
  ContainerOutlined,
  ControlOutlined,
  CopyOutlined,
  CopyrightOutlined,
  CustomerServiceOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  DeleteOutlined,
  DeploymentUnitOutlined,
  DesktopOutlined,
  DownloadOutlined,
  EditOutlined,
  EnvironmentOutlined,
  ExclamationCircleOutlined,
  ExperimentOutlined,
  ExportOutlined,
  EyeOutlined,
  EyeInvisibleOutlined,
  FieldTimeOutlined,
  FileOutlined,
  FileSearchOutlined,
  FileTextOutlined,
  FilterOutlined,
  FireOutlined,
  FlagOutlined,
  FolderOpenOutlined,
  FolderOutlined,
  FormOutlined,
  FunnelPlotOutlined,
  GiftOutlined,
  GlobalOutlined,
  HeartOutlined,
  HistoryOutlined,
  HomeOutlined,
  IdcardOutlined,
  ImportOutlined,
  InboxOutlined,
  InfoCircleOutlined,
  KeyOutlined,
  LaptopOutlined,
  LineChartOutlined,
  LinkOutlined,
  LoadingOutlined,
  LockOutlined,
  MailOutlined,
  MedicineBoxOutlined,
  MenuOutlined,
  MessageOutlined,
  MinusOutlined,
  MobileOutlined,
  MonitorOutlined,
  NodeIndexOutlined,
  NotificationOutlined,
  PaperClipOutlined,
  PartitionOutlined,
  PhoneOutlined,
  PictureOutlined,
  PieChartOutlined,
  PlayCircleOutlined,
  PlusOutlined,
  ProfileOutlined,
  PropertySafetyOutlined,
  QrcodeOutlined,
  QuestionCircleOutlined,
  ReadOutlined,
  ReloadOutlined,
  RocketOutlined,
  SafetyCertificateOutlined,
  SaveOutlined,
  ScheduleOutlined,
  SearchOutlined,
  SendOutlined,
  SettingOutlined,
  ShareAltOutlined,
  ShopOutlined,
  ShoppingCartOutlined,
  ShoppingOutlined,
  SolutionOutlined,
  SoundOutlined,
  StarOutlined,
  SyncOutlined,
  TableOutlined,
  TagOutlined,
  TagsOutlined,
  TeamOutlined,
  ThunderboltOutlined,
  ToolOutlined,
  TrophyOutlined,
  UnorderedListOutlined,
  UploadOutlined,
  UserOutlined,
  VideoCameraOutlined,
  WalletOutlined,
  WifiOutlined,
} from "@ant-design/icons";

const ICON_MAP = {
  HomeOutlined,
  UserOutlined,
  ApartmentOutlined,
  SafetyCertificateOutlined,
  MenuOutlined,
  BookOutlined,
  SettingOutlined,
  LockOutlined,
  MessageOutlined,
  FileTextOutlined,
  ProfileOutlined,
  BankOutlined,
  BellOutlined,
  AuditOutlined,
  TeamOutlined,
  FolderOutlined,
  ToolOutlined,
  DashboardOutlined,
  IdcardOutlined,
  KeyOutlined,
  ReadOutlined,
  ScheduleOutlined,
  CloudOutlined,
  ControlOutlined,
  DeploymentUnitOutlined,
  LinkOutlined,
  EditOutlined,
  DeleteOutlined,
  CopyOutlined,
  SaveOutlined,
  PlusOutlined,
  MinusOutlined,
  CheckOutlined,
  CloseOutlined,
  SearchOutlined,
  FilterOutlined,
  UploadOutlined,
  DownloadOutlined,
  ExportOutlined,
  ImportOutlined,
  ReloadOutlined,
  SyncOutlined,
  BarChartOutlined,
  LineChartOutlined,
  PieChartOutlined,
  AreaChartOutlined,
  TableOutlined,
  AppstoreOutlined,
  AppstoreAddOutlined,
  UnorderedListOutlined,
  CalendarOutlined,
  ClockCircleOutlined,
  FieldTimeOutlined,
  HistoryOutlined,
  NotificationOutlined,
  SoundOutlined,
  VideoCameraOutlined,
  PictureOutlined,
  CameraOutlined,
  FileOutlined,
  FolderOpenOutlined,
  PaperClipOutlined,
  TagsOutlined,
  TagOutlined,
  QrcodeOutlined,
  ContainerOutlined,
  DatabaseOutlined,
  ShoppingOutlined,
  ShoppingCartOutlined,
  ShopOutlined,
  InboxOutlined,
  MailOutlined,
  SendOutlined,
  PhoneOutlined,
  MobileOutlined,
  LaptopOutlined,
  DesktopOutlined,
  GlobalOutlined,
  EnvironmentOutlined,
  FlagOutlined,
  StarOutlined,
  HeartOutlined,
  BulbOutlined,
  FireOutlined,
  ThunderboltOutlined,
  RocketOutlined,
  TrophyOutlined,
  GiftOutlined,
  WalletOutlined,
  PropertySafetyOutlined,
  MedicineBoxOutlined,
  ExperimentOutlined,
  CustomerServiceOutlined,
  CommentOutlined,
  ShareAltOutlined,
  AlertOutlined,
  InfoCircleOutlined,
  QuestionCircleOutlined,
  ExclamationCircleOutlined,
  PartitionOutlined,
  NodeIndexOutlined,
  BranchesOutlined,
  ApiOutlined,
  BugOutlined,
  MonitorOutlined,
  CopyrightOutlined,
  CarryOutOutlined,
  ContactsOutlined,
  SolutionOutlined,
  CompassOutlined,
  BlockOutlined,
  CloudUploadOutlined,
  CodeOutlined,
  FormOutlined,
  FunnelPlotOutlined,
  FileSearchOutlined,
  EyeOutlined,
  EyeInvisibleOutlined,
  WifiOutlined,
  LoadingOutlined,
};

const LEGACY_ICON = {
  user: "UserOutlined",
  setting: "SettingOutlined",
  apartment: "ApartmentOutlined",
  team: "TeamOutlined",
  menu: "MenuOutlined",
};

export function normalizeIconName(raw) {
  if (raw == null) return "";
  return String(raw).trim();
}

export function resolveIconKey(raw) {
  const s = normalizeIconName(raw);
  if (!s) return "";
  if (ICON_MAP[s]) return s;
  const legacy = LEGACY_ICON[s.toLowerCase()];
  if (legacy && ICON_MAP[legacy]) return legacy;
  return "";
}

export function getMenuIcon(raw) {
  const key = resolveIconKey(raw);
  if (!key) return null;
  const Cmp = ICON_MAP[key];
  if (!Cmp) return null;
  return createElement(Cmp);
}

export const MENU_ICON_OPTIONS = Object.keys(ICON_MAP)
  .sort()
  .map((name) => ({ name }));
